### ISSUE TITLE
OnClosed not working

### ISSUE THREAD

**Issue by farzadi** [doghappy/socket.io-client-csharp#14] opened 2019-10-25 17:26 UTC
Hi
I'm using your implementation in my unity project.it's works and I can connect to the server and can emit. but OnClose action not working well when server gets close can't detect the disconnection in the client but it works when I close the client app and I get this message "ClosedByClient".

**Comment by doghappy** [comment] 2019-10-26 08:56
If the connection is disconnected by the server, the `OnClosed` event will be called and the parameter value is **ClosedByServer**. If the server process exits, the `OnClosed` event will be called too and the parameter value is `Aborted`.

According to your description, I can't reproduce it. I would be very grateful if you can help me with it. You can use [this tool](https://amritb.github.io/socketio-client-tool/) to test the server and see what happens.

![image](https://user-images.githubusercontent.com/20038914/67616945-a4d37f00-f810-11e9-8c19-51a1a86fe5f0.png)

**Note: On the server side, I use the `.disconnect()` to disconnect. What about you?**

**Comment by farzadi** [comment] 2019-10-26 09:37
Yes, I test your code and it's work. but what if my server gets down? how your implementation can handle it and client understand the connection is lost and the server is not available?

**Comment by doghappy** [comment] 2019-10-26 09:45
In general, if the connection is closed by server, the server will return a specific code number. But there is still a thread that polls for server status

**Comment by farzadi** [comment] 2019-10-26 14:23
Right, I tested in a console application and it's work. I think it has a problem when running in unity. in unity, can't get the "Aborted" message

**Closed** 2019-12-05 21:31 UTC

**Comment by farshid1** [comment] 2020-05-23 20:28
@farzadi Can you share your sample code for connecting to unity? We are having a difficult time setting that up.
